# Generated by Django 5.2.6 on 2025-12-03 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasehistories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasehistories',
            name='recharge_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.rechargeplan'),
        ),
        migrations.AddField(
            model_name='rechargeplan',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recharge_plans', to='payments.rechargeplancato'),
        ),
        migrations.AddField(
            model_name='sale',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.rechargeplan'),
        ),
    ]
