# Generated by Django 5.2.6 on 2025-12-04 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_purchasehistories_recharge_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistories',
            name='recharge_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.rechargeplan'),
            preserve_default=False,
        ),
    ]
