# Generated by Django 5.2.6 on 2025-12-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgoraCallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('executive_token', models.CharField(default='token', max_length=300)),
                ('token', models.CharField(default='token', max_length=300)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('executive_joined', models.BooleanField(default=False)),
                ('uid', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('joined', 'Joined'), ('missed', 'Missed'), ('left', 'Left'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('coins_deducted', models.PositiveIntegerField(default=0)),
                ('coins_added', models.PositiveIntegerField(default=0)),
                ('last_coin_update_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cleared_by_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CallRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
