# Generated by Django 5.2.6 on 2025-12-03 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0002_initial'),
        ('executives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agoracallhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callrating',
            name='execallhistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='calls.agoracallhistory'),
        ),
        migrations.AddField(
            model_name='callrating',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_ratings', to='executives.executives'),
        ),
        migrations.AddField(
            model_name='callrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talktime',
            name='call_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.agoracallhistory'),
        ),
    ]
