# Generated by Django 5.2.6 on 2025-12-03 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('executives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinredemptionrequest',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executives.executives'),
        ),
    ]
