# Generated by Django 5.2.6 on 2025-12-03 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executives',
            name='user_id',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executiveprofilepicture',
            name='executive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='executives.executives'),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executives.executives'),
        ),
    ]
