# Generated by Django 5.1.1 on 2024-10-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_callhistory_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="callhistory",
            name="zegocloud_call_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
