# Generated by Django 5.1.1 on 2024-10-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_callhistory_zegocloud_call_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
    ]
