# Generated by Django 5.1.1 on 2024-10-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_is_banned_user_is_suspended"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_dormant",
            field=models.BooleanField(default=False),
        ),
    ]
