# Generated by Django 5.1.1 on 2024-10-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_career_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RechargePlanCato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),

        migrations.AddField(
            model_name="rechargeplan",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recharge_plans",
                to="user.rechargeplancato",
            ),
        ),

    ]
