# Generated by Django 5.1.1 on 2024-10-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_rechargeplancato_rechargeplan_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rechargeplan",
            old_name="category",
            new_name="category_id",
        ),
    ]
