# Generated by Django 5.1.1 on 2024-10-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_rename_category_rechargeplan_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rechargeplan",
            old_name="category_id",
            new_name="category",
        ),
    ]
