# Generated by Django 5.1.1 on 2024-11-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_rename_category_id_rechargeplan_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rechargeplan",
            old_name="category",
            new_name="category_id",
        ),
        migrations.AlterField(
            model_name="callhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("missed", "Missed"),
                    ("initiated", "Initiated"),
                    ("accepted", "Accepted"),
                    ("ended", "Ended"),
                ],
                default="missed",
                max_length=10,
            ),
        ),
    ]
