# Generated by Django 5.1 on 2024-10-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('hr_user', 'HR - User'), ('hr_executive', 'HR - Executive'), ('manager_user', 'Manager - User'), ('manager_executive', 'Manager - Executive'), ('superuser', 'Superuser'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallHistoryExe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_start_time', models.DateTimeField(blank=True, null=True)),
                ('call_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('missed', 'Missed'), ('picked', 'Picked')], default='no status', max_length=10)),
                ('coins_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Executives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email_id', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField()),
                ('online', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10)),
                ('coins_per_minute', models.FloatField(default=60.0)),
                ('education_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('executive_id', models.CharField(max_length=50, unique=True)),
                ('set_coin', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coins_balance', models.IntegerField(default=0)),
                ('duty_start_time', models.DateTimeField(blank=True, null=True)),
                ('total_on_duty_seconds', models.PositiveIntegerField(default=0)),
                ('total_talk_seconds_today', models.PositiveIntegerField(default=0)),
                ('total_picked_calls', models.PositiveIntegerField(default=0)),
                ('total_missed_calls', models.PositiveIntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('coins_deducted', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
