# Generated by Django 5.1 on 2024-10-14 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executive', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistoryexe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='callhistoryexe',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executive.executives'),
        ),
        migrations.AddField(
            model_name='talktime',
            name='call_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.callhistory'),
        ),
        migrations.AddField(
            model_name='talktime',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executive.executives'),
        ),
    ]
