# Generated by Django 5.1.1 on 2024-10-14 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callhistoryexe",
            options={
                "verbose_name": "Call History",
                "verbose_name_plural": "Call Histories",
            },
        ),
        migrations.RemoveField(
            model_name="callhistoryexe",
            name="call_end_time",
        ),
        migrations.RemoveField(
            model_name="callhistoryexe",
            name="call_start_time",
        ),
        migrations.RemoveField(
            model_name="callhistoryexe",
            name="status",
        ),
        migrations.RemoveField(
            model_name="callhistoryexe",
            name="user",
        ),
        migrations.AddField(
            model_name="callhistoryexe",
            name="call_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="callhistoryexe",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="callhistoryexe",
            name="coins_earned",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="executives",
            name="mobile_number",
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
