# Generated by Django 5.1.1 on 2024-10-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0003_alter_callhistoryexe_options_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutiveCallHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("coins_earned", models.FloatField(default=0.0)),
                (
                    "call_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.callhistory",
                    ),
                ),
                (
                    "executive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="executive.executives",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CallHistoryExe",
        ),
    ]
