# Generated by Django 5.1.1 on 2024-10-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0004_executivecallhistory_delete_callhistoryexe"),
    ]

    operations = [
        migrations.AddField(
            model_name="executivecallhistory",
            name="status",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
