# Generated by Django 5.1.1 on 2024-10-14 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0005_executivecallhistory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivecallhistory",
            name="status",
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name="CoinRedemptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("upi_id", models.CharField(max_length=255)),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "executive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="executive.executives",
                    ),
                ),
            ],
        ),
    ]
