# Generated by Django 5.1.1 on 2024-10-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0006_alter_executivecallhistory_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivecallhistory",
            name="status",
            field=models.CharField(default="missed", max_length=10),
        ),
    ]
