# Generated by Django 5.1.1 on 2024-10-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0007_alter_executivecallhistory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executives",
            name="is_banned",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="executives",
            name="is_suspended",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
