# Generated by Django 5.1.1 on 2024-10-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0008_alter_executives_is_banned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="executivecallhistory",
            name="zegocloud_call_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
