# Generated by Django 5.1.1 on 2024-10-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0010_revenuetarget_alter_executives_is_banned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenuetarget",
            name="target_talktime",
            field=models.IntegerField(),
        ),
    ]
