# Generated by Django 5.1.1 on 2024-10-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0011_alter_revenuetarget_target_talktime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenuetarget",
            name="target_talktime",
            field=models.DurationField(),
        ),
    ]
