# Generated by Django 5.1.1 on 2024-10-24 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0012_alter_revenuetarget_target_talktime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revenuetarget",
            name="date",
        ),
        migrations.AddField(
            model_name="revenuetarget",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
