# Generated by Django 5.1.1 on 2024-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0013_remove_revenuetarget_date_revenuetarget_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executives",
            name="coins_per_minute",
            field=models.FloatField(default=150.0),
        ),
    ]
