# Generated by Django 5.1.1 on 2024-11-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0014_alter_executives_coins_per_minute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivecallhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("missed", "Missed"),
                    ("initiated", "Initiated"),
                    ("accepted", "Accepted"),
                    ("ended", "Ended"),
                ],
                default="missed",
                max_length=10,
            ),
        ),
    ]
