# Generated by Django 5.1.1 on 2024-11-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0018_executives_user_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="executives",
            old_name="user_profile",
            new_name="user_id",
        ),
    ]
