# Generated by Django 5.1.1 on 2024-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0020_alter_executives_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivecallhistory",
            name="start_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="executivecallhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("accepted", "Accepted"),
                    ("ended", "Ended"),
                    ("missed", "Missed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="executivecallhistory",
            name="zegocloud_call_id",
            field=models.CharField(max_length=255),
        ),
    ]
