# Generated by Django 5.1.1 on 2024-11-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0024_alter_executives_coins_per_second"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executives",
            name="coins_per_second",
            field=models.FloatField(default=3),
        ),
    ]
