# Generated by Django 5.1.1 on 2024-11-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executive", "0025_alter_executives_coins_per_second"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivecallhistory",
            name="coins_earned",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="executives",
            name="coins_balance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
